#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hoberlton School" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://intranet.aluswe.com/users/my_profile permanent;' /etc/nginx/sites-available/default
service nginx start
